### ISSUE TITLE
Automate updating of candidate transaction data

### ISSUE THREAD

**Issue by robertgz** [opensandiego/sdvv-frontend#169]
This will automate the updating of data in the website by shifting to work to GitHub Actions. It will eliminate the need to run `driver_script.js` locally to update the json files and push and merge the changes to the website. This issue is to document the steps being done and the current progress. This will shift the primary location of the csv files from Firebase Storage to GitHub artifacts.

- [x] Revise `download_transactions_to_csv.js` to improve reliability and for it to be configurable from the command line. This is so that is can be used in a Github action workflow. **Completed in #147** 

- [x] Add a Github action to run `download_transactions_to_csv.js` and store the resulting csv file for each year in an artifact in GitHub. The action will support running on demand. After on demand has been tested then it will be scheduled to run daily. **Completed in #152.** 

- [ ] Create a script to download the csv files from the GitHub artifacts. This will use the GitHub API and require an access token to run. This will need to support command line parameters to indicate the years of transaction to download. This script is primarily intended to be run as a Github action as part of the build process. **On hold.**

- [x] Add `npm run update-data` to the Github deployment actions to run before build. This will run `driver_script.js` which uses the csv data to update the json files.  **Completed in #153** 

- [x] Revise `driver_script.js` to add a command line flag to skip downloading the csv files from Firebase Storage.  **Completed in  #173** 

- [ ] Update `npm run update-data -- --skip-download=true` in the Github deployment actions. 

- [ ]  Set GitHub actions to rebuild and deploy the website daily.

**Comment by robertgz** [comment]
The candidate transaction data will be stored in a database in Heroku.
